server:
  port: 8081
spring:
  application:
    #定义应用名称，即服务名称
    name: consumer-server
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: Aa123456
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
    # 连接超时时间（毫秒）
    timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7072/eureka
